@Library('olcne-pipeline') _
import com.oracle.olcne.pipeline.BranchPattern

String coredns_version = "{{{ .major }}}.{{{ .minor }}}.{{{ .patch }}}";
String image_tag = 'v' + coredns_version + '';

olcnePipeline(
        containers: [('container-registry.oracle.com/olcne/coredns:' + image_tag): 'olcne/coredns:' + image_tag],
        branchPattern: new BranchPattern(master: 'oracle/release/' + coredns_version, feature: '(?!^release/.*$)(^.*$)'),
        platforms: ['ol8'],
	architectures: ['x86_64', 'aarch64'],
        yumOL8Repos: ['ol8_appstream'],
	preBuildCommands: [
		'podman pull container-registry.oracle.com/olcne/base:latest',
		'podman tag container-registry.oracle.com/olcne/base:latest container-registry.oracle.com/os/oraclelinux:8',
	],
)
